FROM python:2-buster

RUN apt-get update && apt-get install -y default-libmysqlclient-dev python-dev libsasl2-dev libldap2-dev gcc rsyslog python-pip

RUN useradd -ms /bin/bash -d /dim dim

COPY --chown=dim dim /dim/
COPY --chown=dim dimcfg /etc/dim
COPY --chown=dim .ndclirc .bashrc /root/
COPY --chown=dim docker/entrypoint-dim.sh /dim/entrypoint.sh

USER dim
WORKDIR /dim

RUN pip install -r requirements.txt


ENV SQLALCHEMY_DATABASE_URI ""
ENV AUTHENTICATION_METHOD "None"
ENV LDAP_SERVER ""
ENV LDAP_USER_DN "uid=%s"
ENV LDAP_SEARCH_BASE ""
ENV LDAP_USER_BASE ""
ENV LDAP_DEPARTMENT_BASE ""
ENV SECRET_KEY ""


EXPOSE 5000
ENTRYPOINT ["/dim/entrypoint.sh"]
